feat(otomi normalizer)
ElotlMX/py-elotl pull request #19
Opened 2024-09-20 16:59 UTC by paoinnesb

add normalizer for Otomi with its lexc and att files. Restructure utils/fst/att and changes in makefile

---
name: Pull request
about: 

---

Please include the next info:
- No related issue
- I have added the ortography.py for Otomi, following the convention of the Nahuatl normalizer. For this change, I also updated the Makefile, adding automation to create .att and .lexc files for the Otomi normalizer. I have restructured utils/fst/att, creating two folders (nahuatl and otomi), and added the respective orthographies for each language.
- @Lguyogiro @umoqnier

2024-09-21 01:20 UTC, umoqnier approved these changes
Dejo un par de comments pero en general se ve bastante bien. Buenos docstrings :100: .  Me queda duda si al final no agregamos mas tests y si corrieron los que existen para ver que todo este ok con el código existente que modificaron o que clase de pruebas hicieron para ver que no rompieran nada :question: Si pueden agregar pantallazos a la descripción del PR para que quede documentado vendría joya :)

No mire demasiado los archivos `.att` o `.lexc` se los dejo a @Lguyogiro :p

2024-09-21 01:20 UTC, umoqnier commented on elotl/otomi/orthography.py
> +_available_orthographies = ['inali', 'otq', 'ots', "rfe"]
Creo que si es una variable global conviene que este en mayúsculas
```suggestion
_AVAILABLE_ORTHOGRAPHIES = ['inali', 'otq', 'ots', "rfe"]
```

2024-09-21 01:20 UTC, umoqnier commented on elotl/otomi/orthography.py
> +    TODO: agergar ejemplos correctos
Creo que habría que agregar esto :) ¿Sería en este PR?

2024-09-21 01:20 UTC, umoqnier commented on elotl/otomi/orthography.py
> +            print("Using 'inali' as orthography.")
Creo que esto podría ir con logs como un warning ¿no?

2024-09-21 01:20 UTC, umoqnier commented on elotl/otomi/orthography.py
> +        orthography (currently OTQ, INALI, OTS, and  RFE). Since this process
```suggestion
        orthography (currently OTQ, INALI, OTS, and RFE). Since this process
```

2024-09-21 01:20 UTC, umoqnier commented on elotl/otomi/orthography.py
> +        return s.split()
Quizá dejar un TODO para el futuro para agregar un tokenizador más chido (?) No se si a futuro necesitemos uno diferente. CC: @ximenina, @Lguyogiro

2024-09-21 01:20 UTC, umoqnier commented on elotl/otomi/orthography.py
> +        normalized orthography is OTQ, INALI, OTS, and  RFE. Conversion happens
```suggestion
        normalized orthography is OTQ, INALI, OTS, and RFE. Conversion happens
```

2024-09-21 22:57 UTC, Lguyogiro requested changes
LGTM, se ve muy bien. Antes de hacer el merge yo recomendaría que agreguen unos tests [aquí](https://github.com/ElotlMX/py-elotl/tree/master/tests ).

2024-09-21 22:57 UTC, Lguyogiro commented on elotl/otomi/config.py
> +SUPPORTED_LANG_CODES = ["ote", "inali", "ots", "otq", "rfe"]
creo que esto puede ser un poco confuso porque se están mezclando códigos de la lengua (como "ote") con códigos referentes al sistema de ortografía. Creo que sería mejor cambiar el nombre de este variable o mover los códigos de las ortografías a otra lista. creo que con el Nahuatl hay algo como `_available_orthographies` aparte de las opciones de "language codes" o algo así.

2024-09-21 22:57 UTC, Lguyogiro commented on elotl/otomi/config.py
> +SUPPORTED_LANG_CODES = ["ote", "inali", "ots", "otq", "rfe"]
debo mencionar que lo de los "LANG_CODES" es para cuando tenemos analizadores morfológicos para distintas variantes de una lengua.

2024-09-21 22:57 UTC, Lguyogiro commented on elotl/otomi/orthography.py
> +
TODO :)

2024-09-25 23:53 UTC, ximenina commented on elotl/otomi/orthography.py
> +        return s.split()
Para lenguas que no tienen palabras ortográficas separadas por espacios, esta tokenización puede ser un problema pero por ahora creo que podemos sobrevivir así

2024-10-05 05:15 UTC, paoinnesb commented on elotl/otomi/orthography.py
> +            print("Using 'inali' as orthography.")
ya quedó como warning :)

2024-10-05 05:15 UTC, paoinnesb commented on elotl/otomi/orthography.py
> +    TODO: agergar ejemplos correctos
lo agregaría cuando suba la documentación

2024-10-05 05:15 UTC, paoinnesb commented on elotl/otomi/orthography.py
> +_available_orthographies = ['inali', 'otq', 'ots', "rfe"]
listo 👍

2024-10-05 05:16 UTC, paoinnesb commented
Aún faltan los test del normalizador del otomí, pero espero que estos sean aceptados para agregar los nuevos, y sirve que los subo junto con el update de la documentación

2024-10-07 01:28 UTC, paoinnesb commented
> Se hicieron los siguientes cambios
> 
> * Agregar `AVAILABLE_ORTHOGRAPHIES` como constante en  `config.py` y usarlo en ambos normalizadores (nahuatl y otomi), antes estaba como una variable dentro de cada `orthography.py`. Para el caso del los analizadores tenían un `lang_code` default por lo que también agregué un `DEFAULT_ORTHOGRAPHY` para los normalizadores dentro de config de igual manera
> * Encontré que el uso de `logger.warn()` ya es deprecated por lo que lo cambié por `logger.warning` dentro de los archivos `orthography.py`
> * Cambio de `print()` por `logger.warning()`. En el aviso de la ortografía por default que es usada
> * Cambio de `path()` por `files()`. Debido a que path quedó deprecated, lo hice en todos los archivos que encontré que usaran `path()`
> * Uso de `open()` cuando se abren los archivos para evitar warnings. Al correr los test en el caso de los analizadores morfológicos mandaban muchos warnings lo que hacía difícil ver cuáles eran los verdaderos errores, esto porque no se usaba la lectura de archivos con la función `open()` lo que ocasionaba que los archivos quedaran abiertos
> * Eliminación de `null`. En una parte de los test para el analizador morfologico del nahuatl se usaba `null` en vez de `None`, esto no permitía que el test pudiera ser ejecutado
> 
> Cambios faltantes:
> 
> * Documentación para las normas del nahuatl
> * Test del otomí

<img width="1011" alt="Screenshot 2024-10-06 at 7 26 20 p m" src="https://github.com/user-attachments/assets/b8421ca8-c25b-42cb-b2fa-ec8de8042a00">
Aquí está el screenshot que muestra que las pruebas corren, hay algunas fallas en la parte del analizador del nahuatl pero tengo la teoría que estas nunca han funcionado, ya que al correrlas había un error de sintaxis, eso quedó solucionado pero aún así no pasan

2024-10-07 19:33 UTC, umoqnier reviewed
En general está bien. Dejé unos coments con sugerencias y dudas. Resolviendo esto de mi lado estaría ok

2024-10-07 19:33 UTC, umoqnier commented on elotl/nahuatl/morphology.py
> +				#logger.error("Unsupported language variant specified.")
¿Esto debería estar comentado?

2024-10-07 19:33 UTC, umoqnier commented on elotl/nahuatl/morphology.py
> +		_path_to_tsv_dir = pkg_resources.files("elotl.nahuatl.data").joinpath(f"{self.lang_code}.mor.tsv")
:clap:

2024-10-07 19:33 UTC, umoqnier commented on elotl/utils/fst/attapply.py
> +        except (OSError, TypeError):  # Captura errores específicos si es necesario
```suggestion
        except (OSError, TypeError): 
```

2024-10-07 19:33 UTC, umoqnier commented on elotl/utils/fst/attapply.py
> +        except (OSError, TypeError):  # Captura errores específicos si es necesario
Creo que no es necesario el comentario. En todo caso debería ir en su propia línea y en inglés para ser más abiertos a colaboraciones externas ¿Qué opinas?

2024-10-07 19:33 UTC, umoqnier commented on elotl/utils/morphology.py
> +				score = priority
```suggestion
				score = int(row[0])
```

2024-10-07 19:33 UTC, umoqnier commented on elotl/nahuatl/orthography.py
> +                        "Defaulting to 'sep")
```suggestion
            logger.info(f"No Nahuatl Ortography code provided. "
                        "Defaulting to {DETAULT_ORTOGRAPHY}")
```

2024-10-09 03:49 UTC, paoinnesb commented on elotl/nahuatl/morphology.py
> +				#logger.error("Unsupported language variant specified.")
no jeje, lo descomento

2024-10-09 03:51 UTC, paoinnesb commented on elotl/utils/fst/attapply.py
> +        except (OSError, TypeError):  # Captura errores específicos si es necesario
de acuerdo

2024-10-10 04:45 UTC, Lguyogiro approved these changes
LGTM

2024-10-10 04:50 UTC, Lguyogiro commented
> Aquí está el screenshot que muestra que las pruebas corren, hay algunas fallas en la parte del analizador del nahuatl pero tengo la teoría que estas nunca han funcionado, ya que al correrlas había un error de sintaxis, eso quedó solucionado pero aún así no pasan 

sí funcionaban al principio pero ya se han metido muchos combios desde que se establecieron y al parecer no siempre corríamos los tests jaja. cuando tenga tiempo me pongo a ver esto.

2024-10-10 19:55 UTC, merged